services:
  mysql:
    container_name: fastypest-mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: fastypest
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    expose:
      - "3306"

  postgres:
    container_name: fastypest-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: fastypest
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    expose:
      - "5432"

  mariadb:
    container_name: fastypest-mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3307:3307"
    expose:
      - "3307"

  cockroachdb:
    image: cockroachdb/cockroach:v21.2.8
    container_name: cockroachdb
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    restart: always

  cockroach-init:
    image: cockroachdb/cockroach:v21.2.8
    depends_on:
      - cockroachdb
    entrypoint: /bin/bash -c "until /cockroach/cockroach sql --insecure --host=cockroachdb --execute='SELECT 1'; do sleep 1; done && /cockroach/cockroach sql --insecure --host=cockroachdb --execute='CREATE USER IF NOT EXISTS fastypest; CREATE DATABASE IF NOT EXISTS test; GRANT ALL ON DATABASE test TO fastypest;'"
