name: 🤖 Auto release

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: "0 0 */15 * *"
  workflow_dispatch:

env:
  NODE_VERSION: "18.20"

jobs:
  release:
    name: 🚀 Auto release
    runs-on: ubuntu-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v3
      - name: 🟢 node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.NODE_VERSION }}"
      - name: ⚙️ Install dependencies
        run: yarn install --frozen-lockfile
      - name: 🍃 Create release branch
        run: |
          git checkout -b release/${{ github.run_number }}
          EXISTS=$(git ls-remote --heads origin release/${{ github.run_number }} | wc -l)
          if [ $EXISTS -eq 1 ]; then
            git pull origin release/${{ github.run_number }}
          fi
          git push origin release/${{ github.run_number }}
      - name: 🆙 Bump version and create a git tag
        id: bump_version
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version-type: "patch"
          tag-prefix: "v"
          target-branch: "release/${{ github.run_number }}"
          commit-message: "CI: bumps version to {{version}} [skip ci]"
      - name: 🔀 Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          base: main
          branch: release/${{ github.run_number }}
          title: "Release ${{ steps.bump_version.outputs.newTag }}"
          body: "The version of the code has been bumped to **${{ steps.bump_version.outputs.newTag }}**"
          labels: "auto-release"
      - name: 🧹 Cleanup on failure
        if: ${{ failure() }}
        run: |
          git checkout main
          git branch -D release/${{ github.run_number }}
          git push origin --delete release/${{ github.run_number }}
          git tag -d v${{ steps.bump_version.outputs.newTag }}
          git push origin :refs/tags/v${{ steps.bump_version.outputs.newTag }}
