name: 🤖 Auto release

on:
  schedule:
    - cron: "0 0 */15 * *"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: false

env:
  NODE_VERSION: "18.20"

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v3
      - name: 🟢 node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.NODE_VERSION }}"
      - name: ⚙️ Install dependencies
        run: yarn install --frozen-lockfile
      - name: 🍃 Create release branch
        run: |
          git checkout -b release/${{ github.run_number }}
      - name: 🆙 Bump version and create a git tag
        id: bump_version
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_VERSION: ${{ github.event.inputs.version }}
        with:
          version-type: minor
          tag-prefix: "v"
      - name: 🤖 Push changes
        run: |
          git push origin release/${{ github.run_number }}
      - name: 🪄 Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: release/${{ github.run_number }}
          title: "Release ${{ steps.bump_version.outputs.newTag }}"
          body: "This PR was auto-generated by the GitHub Action workflow **${{ github.workflow }}**. \n\n The version of the code has been bumped to **${{ steps.bump_version.outputs.newTag }}**"
          labels: "auto-release"
      - name: 📦 Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump_version.outputs.newTag }}
          release_name: Release ${{ steps.bump_version.outputs.newTag }}
          draft: false
          prerelease: false
