name: 🗑️ Delete old cache

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  delete-cache:
    runs-on: ubuntu-latest

    steps:
      - name: 🕐 Calculate 7 days ago
        id: subtract-days
        run: echo "::set-output name=date::$(date -u -d '7 days ago' +%Y-%m-%d)"

      - name: 🧹 Delete old cache
        id: delete-old-cache
        run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          /repos/OWNER/REPO/actions/caches \
          -q '.actions_caches[]
              | { id, last_accessed_at }
              | select(.last_accessed_at < ${{ steps.subtract-days.outputs.date }})
              | {id}
              | .[]' \
          --paginate | xargs -I {} \
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/OWNER/REPO/actions/caches/{}
