name: 🗑️ Delete old cache
on:
  workflow_dispatch:
    inputs:
      expired-days:
        description: "Clear cache that has not been used for x days"
        default: ${{ env.default-expired-days }}
        require: true
  schedule:
    - cron: "0 0 * * *"

env:
  default-expired-days: "7"

jobs:
  delete-cache:
    runs-on: ubuntu-latest
    steps:
      - name: 🕐 Calculate ${{ env.default-expired-days || inputs.expired-days }} days ago
        id: subtract-days
        run: echo "date=$(date -u -d '${{ env.default-expired-days || inputs.expired-days }} days ago' +%Y-%m-%dT%H:%M:%SZ%z)" >> $GITHUB_OUTPUT

      - name: 🧹 Delete old cache
        id: delete-old-cache
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${GITHUB_REPOSITORY}/actions/caches \
            -q '.actions_caches[]
                | { id, last_accessed_at }
                | select(.last_accessed_at <= "'"${{ steps.subtract-days.outputs.date }}"'")
                | {id}
                | .[]' \
            --paginate | xargs -I {} \
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${GITHUB_REPOSITORY}/actions/caches/{}
