name: 🚀 Publish to npm
on:
  release:
    types: [published]

env:
  NODE_VERSION: "18.x"

jobs:
  release:
    name: 🆕 Release
    runs-on: ubuntu-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v4
      - name: 🟢 node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.NODE_VERSION }}"
          registry-url: "https://registry.npmjs.org/"
          cache: yarn
      - name: 💾 Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            **/node_modules
            ~/.cache/yarn
          key: yarn-${{ hashFiles('yarn.lock') }}
      - name: ⚙️ yarn install
        run: yarn install --frozen-lockfile
      - name: 🚧 Run build
        run: yarn run build
      - name: 🎉 Publish to npm
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
