name: 🧪 Pull Request tests

on:
  pull_request:
    branches: ["main"]
    types: [opened, reopened, ready_for_review, synchronize]

env:
  NODE_VERSION: "18.x"

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 🚧 Build Node
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: 🔶 Check repository
        uses: actions/checkout@v3
      - name: 🟢 Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: 💾 Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: ⚙️ npm i
        run: npm i
      - name: ⌛ Run build
        run: npm run build

  check-eslint:
    name: 📜 Check format
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: build
    steps:
      - name: 🔶 Check repository
        uses: actions/checkout@v3
      - name: 🟢 Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: 💾 Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: ✔️ Run eslint
        run: npm run eslint

  all-test-ok:
    name: ✅ Check all test
    runs-on: ubuntu-latest
    needs: run-test
    if: ${{ success() }}
    outputs:
      success: ${{ steps.all-ok.outputs.success }}
    steps:
      - id: all-ok
        run: echo "success=true" >> $GITHUB_OUTPUT

  run-test:
    name: 🗂️ ${{ matrix.database.name }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build
    strategy:
      fail-fast: false
      matrix:
        database:
          - name: cockroachdb - 22.2.0
            type: cockroachdb
            use-service: false
            image: cockroachdb/cockroach:v22.2.0
            port: 26257
            run: |
              docker pull cockroachdb/cockroach:v22.2.0
              docker run -d --name roach --hostname roach \
                -p 26257:26257 -p 8080:8080 \
                -e "COCKROACH_INSECURE=true" \
                -e "COCKROACH_USER=root" \
                -e "COCKROACH_PASSWORD=password" \
                cockroachdb/cockroach:v22.2.0 start-single-node --insecure
              sudo apt update && sudo apt install wait-for-it -y
              wait-for-it -h localhost -p 26257
              docker exec roach bash -c "echo 'CREATE DATABASE test;' | cockroach sql --insecure"

          - name: cockroachdb - latest
            type: cockroachdb
            use-service: false
            image: cockroachdb/cockroach:latest
            port: 26257
            run: |
              docker pull cockroachdb/cockroach:latest
              docker run -d --name roach --hostname roach \
                -p 26257:26257 -p 8080:8080 \
                -e "COCKROACH_INSECURE=true" \
                -e "COCKROACH_USER=root" \
                -e "COCKROACH_PASSWORD=password" \
                cockroachdb/cockroach:latest start-single-node --insecure
              sudo apt update && sudo apt install wait-for-it -y
              wait-for-it -h localhost -p 26257
              docker exec roach bash -c "echo 'CREATE DATABASE test;' | cockroach sql --insecure"

          - name: mysql - 5.7
            type: mysql
            use-service: true
            service:
              image: "bitnami/mysql:5.7"
              env:
                MYSQL_ROOT_PASSWORD: password
                MYSQL_ALLOW_EMPTY_PASSWORD: 1
                MYSQL_DATABASE: test
                MYSQL_ROOT_HOST: "%"
                MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
              ports:
                - 3306:3306
              options: >-
                --health-cmd="mysqladmin ping"
                --health-interval=10s
                --health-timeout=5s
                --health-retries=3

          - name: mysql - latest
            type: mysql
            use-service: true
            service:
              image: "bitnami/mysql:latest"
              env:
                MYSQL_ROOT_PASSWORD: password
                MYSQL_ALLOW_EMPTY_PASSWORD: 1
                MYSQL_DATABASE: test
                MYSQL_ROOT_HOST: "%"
                MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
              ports:
                - 3306:3306
              options: >-
                --health-cmd="mysqladmin ping"
                --health-interval=10s
                --health-timeout=5s
                --health-retries=3

          - name: postgres - 9.4.6
            type: postgres
            use-service: true
            service:
              image: "bitnami/postgresql:9.4.6"
              env:
                POSTGRES_PASSWORD: password
                POSTGRES_USER: root
                POSTGRES_DB: test
              ports:
                - 5432:5432
              options: >-
                --health-cmd="pg_isready"
                --health-interval=12s
                --health-timeout=7s
                --health-retries=3

          - name: postgres - latest
            type: postgres
            use-service: true
            service:
              image: "postgres"
              env:
                POSTGRES_PASSWORD: password
                POSTGRES_USER: root
                POSTGRES_DB: test
              ports:
                - 5432:5432
              options: >-
                --health-cmd="pg_isready"
                --health-interval=12s
                --health-timeout=7s
                --health-retries=3

          - name: mariadb - 10.11
            type: mariadb
            use-service: true
            service:
              image: "mariadb:10.11"
              env:
                MARIADB_ROOT_PASSWORD: password
                MARIADB_DATABASE: test
                MARIADB_ROOT_HOST: "%"
              ports:
                - 3306:3306
              options: >-
                --health-cmd="mysqladmin ping"
                --health-interval=12s
                --health-timeout=7s
                --health-retries=3

          - name: mariadb - latest
            type: mariadb
            use-service: true
            service:
              image: "mariadb:latest"
              env:
                MARIADB_ROOT_PASSWORD: password
                MARIADB_DATABASE: test
                MARIADB_ROOT_HOST: "%"
              ports:
                - 3306:3306
              options: >-
                --health-cmd="healthcheck.sh --connect --innodb_initialized"
                --health-interval=12s
                --health-timeout=7s
                --health-retries=3

    services:
      data-base: ${{matrix.database.service}}

    steps:
      - if: ${{matrix.database.use-service == false}}
        name: 🐋 Start a single instance with docker
        run: ${{ matrix.database.run }}
      - name: 🔶 Check repository
        uses: actions/checkout@v3
      - name: 🟢 Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: 💾 Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: 🧪 Testing
        env:
          DB_TYPE: ${{ matrix.database.type }}
          DB_PORT: ${{ matrix.database.port }}
        run: npm run test
